cluster:
  user: ${CLUSTER_USER}
  endpoint: ${CLUSTER_ENDPOINT}

app:
  exit-after-test: ${EXIT_AFTER_TEST:false}

spring:
  datasource:
    url: jdbc:aws-dsql:postgresql://${cluster.endpoint}
    username: ${cluster.user}
    driver-class-name: software.amazon.dsql.jdbc.DSQLConnector
    hikari:
      max-lifetime: 600000         # 10 minutes (shorter than default token expiry)
      minimum-idle: 2
      maximum-pool-size: 10
      idle-timeout: 300000         # 5 minutes
      connection-timeout: 30000    # 30 seconds
      validation-timeout: 5000     # 5 seconds
      connection-test-query: "SELECT 1"
      data-source-properties:
        sslmode: verify-full
        sslfactory: org.postgresql.ssl.DefaultJavaSSLFactory
        sslnegotiation: direct
