spring:
  datasource:
    url: jdbc:aws-dsql:postgresql://${CLUSTER_ENDPOINT}/postgres
    username: ${CLUSTER_USER}
    driver-class-name: software.amazon.dsql.jdbc.DSQLConnector
    hikari:
      data-source-properties:
        token-duration-secs: 28800  # 8 hours
        profile: ${PROFILE}        # Optional: AWS profile for authentication
      max-lifetime: 3000000        # 50 minutes (shorter than Aurora DSQL's 60-minute limit)
      minimum-idle: 2
      maximum-pool-size: 10
      idle-timeout: 300000         # 5 minutes
      connection-timeout: 30000    # 30 seconds
      validation-timeout: 5000     # 5 seconds
      connection-test-query: "SELECT 1"
logging:
  level:
    software.amazon.dsql: DEBUG
