name: Java pgJDBC integration tests

permissions: {}

on:
  push:
    branches: [main]
    paths:
      - "java/pgjdbc_hikaricp/**"
      - ".github/workflows/java-pgjdbc-hikari-integcp-tests.yml"
  pull_request:
    branches: [main]
    paths:
      - "java/pgjdbc_hikaricp/**"
      - ".github/workflows/java-pgjdbc-hikari-integcp-tests.yml"
  # Give us a button to allow running the workflow on demand for testing.
  workflow_dispatch:
    inputs:
      tags:
        description: "Manual Workflow Run"
        required: false
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # required by aws-actions/configure-aws-credentials
    concurrency:
      # Ensure only 1 job uses the workflow cluster at a time.
      group: ${{ github.workflow }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "corretto"
          architecture: x64
          cache: maven

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.JAVA_IAM_ROLE }}
          aws-region: us-east-1

      - name: Configure and run integration for pgjdbc - admin
        working-directory: ./java/pgjdbc_hikaricp
        env:
          CLUSTER_ENDPOINT: ${{ secrets.JAVA_PGJDBC_HIKARI_CLUSTER_ENDPOINT }}
          CLUSTER_USER: admin
          REGION: ${{ secrets.JAVA_PGJDBC_HIKARI_CLUSTER_REGION }}
        run: |
          mvn validate
          mvn initialize
          mvn clean compile assembly:single
          mvn test
